[build]
    command = "npm run build"
    functions = "src/api"
    publish = "dist"
    environment = { NODE_VERSION = "14" }

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
        Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"