name: Lint and Fix

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
    lint:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'

            - name: Install dependencies
              run: npm install
    
            - name: Run ESLint and fix
              run: npm run lint:fix
    
            - name: Commit changes
              run: |
                git config --global user.email "
                git config --global user.name "GitHub Actions"
                git commit -am "Lint and fix"
                git push
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            