name: Track Ticket Completion

on:
  pull_request:
    types: [closed]

jobs:
  update-points:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Update Points Script
        if: ${{ github.event.pull_request.merged }}
        run: |
          python scripts/update_points_docs.py "${{ github.actor }}" 30 "completed"

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/team-points.md
          git commit -m "Update points for ${GITHUB_ACTOR}"
          git push
